EducateApp/ViewModels/TypesOfTotals/CreateTypeOfTotalViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace EducateApp.ViewModels.TypesOfTotals
{
    public class CreateTypeOfTotalViewModel
    {
        [Required(ErrorMessage = "Введите название аттестации")]
        [Display(Name = "Название аттестации")]
        public string CertificateName { get; set; }
    }
}

EducateApp/ViewModels/TypesOfTotals/EditTypeOfTotalViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace EducateApp.ViewModels.TypesOfTotals
{
    public class EditTypeOfTotalViewModel
    {
        public short Id { get; set; }

        [Required(ErrorMessage = "Введите название аттестации")]
        [Display(Name = "Название аттестации")]
        public string CertificateName { get; set; }

        public string IdUser { get; set; }
    }
}

EducateApp/Controllers/TypesOfTotalsController.cs
using EducateApp.Models;
using EducateApp.Models.Data;
using EducateApp.Models.Enums;
using EducateApp.ViewModels.TypesOfTotals;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace EducateApp.Controllers
{
    [Authorize(Roles = "admin, registeredUser")]
    public class TypesOfTotalsController : Controller
    {
        private readonly ApplicationContext _context;
        private readonly UserManager<User> _userManager;

        public TypesOfTotalsController(ApplicationContext context, UserManager<User> user)
        {
            _context = context;
            _userManager = user;
        }

        // GET: TypesOfTotals
        public async Task<IActionResult> Index(TypeOfTotalSortState sortOrder = TypeOfTotalSortState.CertificateNameAsc)
        {
            // находим информацию о пользователе, который вошел в систему по его имени
            IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            // через контекст данных получаем доступ к таблице
            var typesOfTotals = _context.TypesOfTotals
                .Include(i => i.User)
                .Where(w => w.IdUser == user.Id);

            ViewData["CertificateNameSort"] = sortOrder == TypeOfTotalSortState.CertificateNameAsc ? TypeOfTotalSortState.CertificateNameDesc : TypeOfTotalSortState.CertificateNameAsc;

            typesOfTotals = sortOrder switch
                {
                    TypeOfTotalSortState.CertificateNameDesc => typesOfTotals.OrderByDescending(s => s.CertificateName),
                    _ => typesOfTotals.OrderBy(s => s.CertificateName),
                };

            // возвращаем в представление полученный список записей
            return View(await typesOfTotals.AsNoTracking().ToListAsync());
        }

        // GET: TypesOfTotals/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TypesOfTotals/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateTypeOfTotalViewModel model)
        {
            IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            if (_context.TypesOfTotals
                .Where(f => f.IdUser == user.Id &&
                    f.CertificateName == model.CertificateName).FirstOrDefault() != null)
            {
                ModelState.AddModelError("", "Введенный вид промежуточной аттестации уже существует");
            }

            if (ModelState.IsValid)
            {
                TypeOfTotal typeOfTotal = new()
                {
                    CertificateName = model.CertificateName,
                    IdUser = user.Id
                };

                _context.Add(typeOfTotal);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: TypesOfTotals/Edit/5
        public async Task<IActionResult> Edit(short? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var typeOfTotal = await _context.TypesOfTotals.FindAsync(id);
            if (typeOfTotal == null)
            {
                return NotFound();
            }

            EditTypeOfTotalViewModel model = new()
            {
                Id = typeOfTotal.Id,
                CertificateName = typeOfTotal.CertificateName,
                IdUser = typeOfTotal.IdUser
            };

            return View(model);
        }

        // POST: TypesOfTotals/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(short id, EditTypeOfTotalViewModel model)
        {
            TypeOfTotal typeOfTotal = await _context.TypesOfTotals.FindAsync(id);

            if (id != typeOfTotal.Id)
            {
                return NotFound();
            }

            IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            if (_context.TypesOfTotals
                .Where(f => f.IdUser == user.Id &&
                    f.CertificateName == model.CertificateName).FirstOrDefault() != null)
            {
                ModelState.AddModelError("", "Введенный вид промежуточной аттестации уже существует");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    typeOfTotal.CertificateName = model.CertificateName;
                    _context.Update(typeOfTotal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TypeOfTotalExists(typeOfTotal.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: TypesOfTotals/Delete/5
        public async Task<IActionResult> Delete(short? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var typeOfTotal = await _context.TypesOfTotals
                .Include(t => t.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (typeOfTotal == null)
            {
                return NotFound();
            }

            return View(typeOfTotal);
        }

        // POST: TypesOfTotals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(short id)
        {
            var typeOfTotal = await _context.TypesOfTotals.FindAsync(id);
            _context.TypesOfTotals.Remove(typeOfTotal);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: TypesOfTotals/Details/5
        public async Task<IActionResult> Details(short? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var typeOfTotal = await _context.TypesOfTotals
                .Include(t => t.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (typeOfTotal == null)
            {
                return NotFound();
            }

            return PartialView(typeOfTotal);
        }

        private bool TypeOfTotalExists(short id)
        {
            return _context.TypesOfTotals.Any(e => e.Id == id);
        }
    }
}

EducateApp/Views/TypesOfTotals/Create.cshtml
@model EducateApp.ViewModels.TypesOfTotals.CreateTypeOfTotalViewModel

@{
    ViewData["Title"] = "Создание - Виды промежуточной аттестации";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item"><a asp-controller="TypesOfTotals" asp-action="Index">Виды промежуточной аттестации</a></li>
        <li class="breadcrumb-item active">Создание</li>
    </ol>
</nav>

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Добавление вида промежуточной аттестации
</h3>
<hr />

<div class="row">
    <div class="col-md-5">
        <form method="post" asp-controller="TypesOfTotals" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CertificateName" class="control-label"></label>
                <input asp-for="CertificateName" class="form-control" />
                <span asp-validation-for="CertificateName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EducateApp/Views/TypesOfTotals/Delete.cshtml
@model EducateApp.Models.Data.TypeOfTotal

@{
    ViewData["Title"] = "Удаление - Виды промежуточной аттестации";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item"><a asp-controller="TypesOfTotals" asp-action="Index">Виды промежуточной аттестации</a></li>
        <li class="breadcrumb-item active">Удаление</li>
    </ol>
</nav>

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Удаление вида промежуточной аттестации
</h3>

<div>
    <h4>
        Вы уверены, что желаете удалить запись?<br />
        Все связанные данные будут удалены!
    </h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.CertificateName)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.CertificateName)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" />
    </form>
</div>

EducateApp/Views/TypesOfTotals/Details.cshtml
@model EducateApp.Models.Data.TypeOfTotal

<div class="modal-content">
    <div class="modal-header">
        <h4 class="modal-title">Просмотр группы</h4>
        <button type="button" class="close" data-dismiss="modal">
            <i class="fas fa-times"></i>
        </button>
    </div>

    <div class="modal-body">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.CertificateName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.CertificateName)
            </dd>
        </dl>
    </div>
</div>

EducateApp/Views/TypesOfTotals/Edit.cshtml
@model EducateApp.ViewModels.TypesOfTotals.EditTypeOfTotalViewModel

@{
    ViewData["Title"] = "Изменение - Виды промежуточной аттестации";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item"><a asp-controller="TypesOfTotals" asp-action="Index">Виды промежуточной аттестации</a></li>
        <li class="breadcrumb-item active">Изменение</li>
    </ol>
</nav>

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Изменение вида промежуточной аттестации
</h3>
<hr />

<div class="row">
    <div class="col-md-5">
        <form asp-controller="TypesOfTotals" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CertificateName" class="control-label"></label>
                <input asp-for="CertificateName" class="form-control" />
                <span asp-validation-for="CertificateName" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="IdUser" />
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EducateApp/Views/TypesOfTotals/Index.cshtml
@model IEnumerable<EducateApp.Models.Data.TypeOfTotal>

@{
    ViewData["Title"] = "Виды промежуточной аттестации";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item active">Виды промежуточной аттестации</li>
    </ol>
</nav>
<h2>Виды промежуточной аттестации</h2>

<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog"></div>
</div>

<h6>
    <a class="btn text-dark" asp-action="Create">
        <i class="far fa-plus-square"></i>  Добавить вид промежуточной аттестации
    </a>
</h6>
<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewBag.CertificateNameSort">
                    @Html.DisplayNameFor(model => model.CertificateName)
                </a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CertificateName)
                </td>
                <td>
                    <a class="btn text-dark details" asp-action="Details" asp-route-id="@item.Id" title="Посмотреть подробнее" id="details">
                        <i class="far fa-eye"></i>
                    </a> |
                    <a class="btn text-dark" asp-action="Edit" asp-route-id="@item.Id" title="Редактировать">
                        <i class="fas fa-pencil-alt"></i>
                    </a> |
                    <a class="btn text-dark" asp-action="Delete" asp-route-id="@item.Id" title="Удалить">
                        <i class="far fa-minus-square"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts
{
    <script type="text/javascript">
        $(function () {
           $.ajaxSetup({ cache: false });
            $(".details").click(function (e) {
                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
        })
    </script>
}