EducateApp/Controllers/GroupsController.cs
using ClosedXML.Excel;
using EducateApp.Models;
using EducateApp.Models.Data;
using EducateApp.ViewModels.Groups;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace EducateApp.Controllers
{
    [Authorize(Roles = "admin, registeredUser")]
    public class GroupsController : Controller
    {
        private readonly ApplicationContext _context;
        private readonly UserManager<User> _userManager;

        public GroupsController(ApplicationContext context, UserManager<User> user)
        {
            _context = context;
            _userManager = user;
        }

        // GET: Groups
        public async Task<IActionResult> Index()
        {
            IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            var appCtx = _context.Groups
                .Include(s => s.Specialty.FormOfStudy)
                .Where(w => w.Specialty.FormOfStudy.IdUser == user.Id)
                .OrderByDescending(f => f.YearOfAdmission)
                .ThenBy(f => f.YearOfIssue)
                .ThenByDescending(f => f.Name);

            return View(await appCtx.ToListAsync());
        }


        // GET: Groups/Create
        public async Task<IActionResult> CreateAsync()
        {
            IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            // переменная для хранения выбранного номера по списку по умолчанию
            short selectedIndex = 1;

            // создание выпадающего списка Форм обучения, в качестве аргументов:
            // элементы списка, номер элемента списка, его название и номер выбранного элемента
            SelectList formsOfStudy = new(await _context.FormsOfStudy
               .Where(w => w.IdUser == user.Id)
               .OrderBy(o => o.FormOfEdu).ToListAsync(),
               "Id", "FormOfEdu", selectedIndex);

            // передаем настроенный список с помощью ViewBag
            ViewBag.FormsOfStudy = formsOfStudy;

            // создание выпадающего списка Специальностей, который зависим от списка с Формами обучения
            // в качестве аргументов:
            // элементы списка (для текущей формы обучения), номер элемента списка, его название
            SelectList specialties = new(await _context.Specialties
                .Where(w => w.FormOfStudy.IdUser == user.Id && w.IdFormOfStudy == selectedIndex)
                .OrderBy(o => o.Code).ToListAsync(),
                "Id", "Code");

            // передаем настроенный список с помощью ViewBag
            ViewBag.Specialties = specialties;
            return View();
        }

        public async Task<IActionResult> GetItemsAsync(short id)
        {
            IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            // с помощью частичного представления снова возвращаем список с элементами
            // (специальности для выбранного пользователем элемента списка формы обчения)
            return PartialView(
                _context.Specialties
                .Where(w => w.FormOfStudy.IdUser == user.Id && w.IdFormOfStudy == id)
                .OrderBy(o => o.Code).ToList());
        }

        // POST: Groups/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateGroupViewModel model)
        {
            IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            if (_context.Groups
                .Where(f => f.Specialty.FormOfStudy.IdUser == user.Id &&
                    f.Name == model.Name &&
                    f.ClassTeacher == model.ClassTeacher &&
                    f.YearOfAdmission == model.YearOfAdmission &&
                    f.YearOfIssue == model.YearOfIssue &&
                    f.IdSpecialty == model.IdSpecialty).FirstOrDefault() != null)
            {
                ModelState.AddModelError("", "Введеная группа уже существует");
            }

            if (model.YearOfIssue < model.YearOfAdmission)
            {
                ModelState.AddModelError("", "Год выпуска должен быть больше, чем год поступления");
            }

            if (ModelState.IsValid)
            {
                Group group = new()
                {
                    IdSpecialty = model.IdSpecialty,
                    Name = model.Name,
                    CountOfStudents = model.CountOfStudents,
                    YearOfAdmission = model.YearOfAdmission,
                    YearOfIssue = model.YearOfIssue,
                    ClassTeacher = model.ClassTeacher,
                    ContactsTeacher = model.ContactsTeacher
                };

                _context.Add(group);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            short selectedIndex = 1;

            SelectList formsOfStudy = new(await _context.FormsOfStudy
               .Where(w => w.IdUser == user.Id)
               .OrderBy(o => o.FormOfEdu).ToListAsync(),
               "Id", "FormOfEdu", selectedIndex);

            ViewBag.FormsOfStudy = formsOfStudy;

            SelectList specialties = new(await _context.Specialties
                .Where(w => w.FormOfStudy.IdUser == user.Id && w.IdFormOfStudy == selectedIndex)
                .OrderBy(o => o.Code).ToListAsync(),
                "Id", "Code");

            ViewBag.Specialties = specialties;

            return View(model);
        }

        // GET: Groups/Edit/5
        public async Task<IActionResult> Edit(short? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var group = await _context.Groups.FindAsync(id);
            if (group == null)
            {
                return NotFound();
            }

            short idFormOfStudy = await _context.Specialties
                .Where(w => w.Id == group.IdSpecialty)
                .Select(s => s.IdFormOfStudy)
                .FirstOrDefaultAsync();

            EditGroupViewModel model = new()
            {
                Id = group.Id,
                IdFormOfStudy = idFormOfStudy,
                IdSpecialty = group.IdSpecialty,
                Name = group.Name,
                CountOfStudents = group.CountOfStudents,
                YearOfAdmission = group.YearOfAdmission,
                YearOfIssue = group.YearOfIssue,
                ClassTeacher = group.ClassTeacher,
                ContactsTeacher = group.ContactsTeacher
            };

            IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            SelectList formsOfStudy = new(await _context.FormsOfStudy
               .Where(w => w.IdUser == user.Id)
               .OrderBy(o => o.FormOfEdu).ToListAsync(),
               "Id", "FormOfEdu", idFormOfStudy);

            ViewBag.FormsOfStudy = formsOfStudy;

            SelectList specialties = new(await _context.Specialties
                .Where(w => w.FormOfStudy.IdUser == user.Id && w.IdFormOfStudy == idFormOfStudy)
                .OrderBy(o => o.Code).ToListAsync(),
                "Id", "Code");

            ViewBag.Specialties = specialties;

            return View(model);
        }

        // POST: Groups/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(short id, EditGroupViewModel model)
        {
            IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            Group group = await _context.Groups.FindAsync(id);

            if (id != group.Id)
            {
                return NotFound();
            }

            if (_context.Groups
                .Where(f => f.Specialty.FormOfStudy.IdUser == user.Id &&
                    f.Name == model.Name &&
                    f.ClassTeacher == model.ClassTeacher &&
                    f.YearOfAdmission == model.YearOfAdmission &&
                    f.YearOfIssue == model.YearOfIssue &&
                    f.IdSpecialty == model.IdSpecialty).FirstOrDefault() != null)
            {
                ModelState.AddModelError("", "Введеная группа уже существует");
            }

            if (model.YearOfIssue < model.YearOfAdmission)
            {
                ModelState.AddModelError("", "Год выпуска должен быть больше, чем год поступления");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    group.IdSpecialty = model.IdSpecialty;
                    group.Name = model.Name;
                    group.CountOfStudents = model.CountOfStudents;
                    group.YearOfAdmission = model.YearOfAdmission;
                    group.YearOfIssue = model.YearOfIssue;
                    group.ClassTeacher = model.ClassTeacher;
                    group.ContactsTeacher = model.ContactsTeacher;
                    _context.Update(group);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GroupExists(group.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            SelectList formsOfStudy = new(await _context.FormsOfStudy
               .Where(w => w.IdUser == user.Id)
               .OrderBy(o => o.FormOfEdu).ToListAsync(),
               "Id", "FormOfEdu", model.IdFormOfStudy);

            ViewBag.FormsOfStudy = formsOfStudy;

EducateApp/Controllers/UsersController.cs
using EducateApp.Models;
using EducateApp.ViewModels.Users;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EducateApp.Controllers
{
    [Authorize(Roles = "admin")]
    public class UsersController : Controller
    {
        UserManager<User> _userManager;
        RoleManager<IdentityRole> _roleManager;

        public UsersController(UserManager<User> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public IActionResult Index() => View(_userManager.Users.ToList());

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = new User
                {
                    Email = model.Email,
                    UserName = model.Email,
                    LastName = model.LastName,
                    FirstName = model.FirstName,
                    Patronymic = model.Patronymic
                };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }


        public async Task<IActionResult> Edit(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            EditUserViewModel model = new EditUserViewModel
            {
                Id = user.Id,
                Email = user.Email,
                LastName = user.LastName,
                FirstName = user.FirstName,
                Patronymic = user.Patronymic
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    user.Email = model.Email;
                    user.UserName = model.Email;
                    user.LastName = model.LastName;
                    user.FirstName = model.FirstName;
                    user.Patronymic = model.Patronymic;

                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }
            return View(model);
        }


        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            IdentityResult result = await _userManager.DeleteAsync(user);
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> ChangePassword(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            ChangePasswordViewModel model = new ChangePasswordViewModel
            {
                Id = user.Id,
                Email = user.Email
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    var _passwordValidator =
                        HttpContext.RequestServices.GetService(typeof(IPasswordValidator<User>)) as IPasswordValidator<User>;
                    var _passwordHasher =
                        HttpContext.RequestServices.GetService(typeof(IPasswordHasher<User>)) as IPasswordHasher<User>;

                    IdentityResult result =
                        await _passwordValidator.ValidateAsync(_userManager, user, model.NewPassword);
                    if (result.Succeeded)
                    {
                        user.PasswordHash = _passwordHasher.HashPassword(user, model.NewPassword);
                        await _userManager.UpdateAsync(user);
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Пользователь не найден");
                }
            }
            return View(model);
        }



        public async Task<IActionResult> EditRoles(string userId)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> EditRoles(string userId, List<string> roles)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = _roleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction(nameof(Index));
            }

            return NotFound();
        }
    }
}

EducateApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EducateApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 fixed-top">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (IsSectionDefined("Header"))
                    {
                        @RenderSection("Header")
                    }
                    else
                    {
                        // если пользователь IsAuthenticated
                        @if (User.Identity.IsAuthenticated)
                        {
                            // то он видит вкладку "Главная"
                            <ul class="navbar-nav flex-grow">
                                <li>
                                    <a class="nav-link text-dark" asp-controller="Home" asp-action="Index" title="Главная">
                                        <i class="fas fa-home"></i>
                                    </a>
                                </li>

                                @*если пользователь с ролью админ, то он получает доступ к работе со всеми пользователями системы*@
                                @if (User.Claims.Where(c => c.Type == System.Security.Claims.ClaimTypes.Role).Select(s => s.Value).Contains("admin"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-controller="Users" asp-action="Index" title="Пользователи">
                                            <i class="far fa-user"></i>  Пользователи
                                        </a>
                                    </li>
                                }

                                <li class="nav-item dropdown">
                                    <a class="nav-link text-dark dropdown-toggle" data-toggle="dropdown">
                                        <i class="fas fa-chalkboard-teacher"></i>  Информация об обучении
                                    </a>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item text-dark" asp-controller="FormsOfStudy" asp-action="Index">Формы обучения</a>
                                        <a class="dropdown-item text-dark" asp-controller="Specialties" asp-action="Index">Специальности</a>
                                        <a class="dropdown-item text-dark" asp-controller="Groups" asp-action="Index">Группы</a>
                                        <a class="dropdown-item text-dark" asp-controller="Disciplines" asp-action="Index">Дисциплины</a>
                                        <a class="dropdown-item text-dark" asp-controller="TypesOfTotals" asp-action="Index">Виды промежуточной аттестации</a>
                                    </div>
                                </li>
                            </ul>

                            // с левой стороны, пользователь видит свой свою почту с выпадающим меню
                            // одним из пунктов меню является выход
                            <ul class="navbar-nav flex-grow">
                                <li class="nav-item dropdown">
                                    <a class="nav-link text-dark dropdown-toggle" data-toggle="dropdown">
                                        <i class="far fa-user-circle"></i>  @User.Identity.Name
                                    </a>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item text-dark" asp-controller="PersonalInfos" asp-action="Index">Личные данные</a>
                                        <div class="dropdown-item ">
                                            <form class="form-inline" method="post" asp-controller="Account" asp-action="Logout">
                                                <div class="form-group">
                                                    <i class="fas fa-sign-out-alt"></i>
                                                    <input class="btn btn-link text-dark" type="submit" value="Выход" />
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </li>
                            </ul>

                        }
                        // если пользователь не вошел на сайт, то для него отображается в качестве главной страницы вход в систему
                        else
                        {
                            <ul class="navbar-nav">
                                <li>
                                    <a class="nav-link text-dark" asp-controller="Account" asp-action="Login" title="Главная">
                                        <i class="fas fa-home"></i>
                                    </a>
                                </li>
                            </ul>
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Account" asp-action="Login">
                                        <i class="fas fa-sign-in-alt"></i>  Вход
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Account" asp-action="Register">Регистрация</a>
                                </li>
                            </ul>
                        }
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container" style="margin-top:80px">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Today.Year - EducateApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>