EducateApp/Models/Data/Specialty.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EducateApp.Models.Data
{
    public class Specialty
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Display(Name = "ИД")]
        public short Id { get; set; }

        [Required(ErrorMessage = "Введите индекс специальности")]
        [Display(Name = "Индекс")]
        public string Code { get; set; }

        [Required(ErrorMessage = "Введите название специальности")]
        [Display(Name = "Специальность")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Форма обучения")]
        public short IdFormOfStudy { get; set; }


        // Навигационные свойства
        [Display(Name = "Форма обучения")]
        [ForeignKey("IdFormOfStudy")]
        public FormOfStudy FormOfStudy { get; set; }

        public ICollection<Group> Groups { get; set; }
    }
}

EducateApp/ViewModels/Specialties/CreateSpecialtyViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace EducateApp.ViewModels.Specialties
{
    public class CreateSpecialtyViewModel
    {
        [Required(ErrorMessage = "Введите индекс специальности")]
        [Display(Name = "Индекс")]
        public string Code { get; set; }

        [Required(ErrorMessage = "Введите название специальности")]
        [Display(Name = "Специальность")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Форма обучения")]
        public short IdFormOfStudy { get; set; }
    }
}

EducateApp/ViewModels/Specialties/EditSpecialtyViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace EducateApp.ViewModels.Specialties
{
    public class EditSpecialtyViewModel
    {
        public short Id { get; set; }

        [Required(ErrorMessage = "Введите индекс специальности")]
        [Display(Name = "Индекс")]
        public string Code { get; set; }

        [Required(ErrorMessage = "Введите название специальности")]
        [Display(Name = "Специальность")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Форма обучения")]
        public short IdFormOfStudy { get; set; }
    }
}

EducateApp/ViewModels/Specialties/FilterSpecialtyViewModel.cs
using EducateApp.Models.Data;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace EducateApp.ViewModels.Specialties
{
    public class FilterSpecialtyViewModel
    {
        public string SelectedCode { get; private set; }    // введенный код
        public string SelectedName { get; private set; }    // введенное имя

        public SelectList FormOfStudies { get; private set; } // список форм обучения
        public short? FormOfEdu { get; private set; }   // выбранная форма обучения


        public FilterSpecialtyViewModel(string code, string name,
            List<FormOfStudy> formOfStudies, short? formOfEdu)
        {
            SelectedCode = code;
            SelectedName = name;

            // устанавливаем начальный элемент, который позволит выбрать всех
            formOfStudies.Insert(0, new FormOfStudy { FormOfEdu = "", Id = 0 });

            FormOfStudies = new SelectList(formOfStudies, "Id", "FormOfEdu", formOfEdu);
            FormOfEdu = formOfEdu;
        }
    }
}

EducateApp/ViewModels/Specialties/IndexSpecialtyViewModel.cs
using EducateApp.Models.Data;
using System.Collections.Generic;

namespace EducateApp.ViewModels.Specialties
{
    public class IndexSpecialtyViewModel
    {
        public IEnumerable<Specialty> Specialties { get; set; }
        public PageViewModel PageViewModel { get; set; }
        public FilterSpecialtyViewModel FilterSpecialtyViewModel { get; set; }
        public SortSpecialtyViewModel SortSpecialtyViewModel { get; set; }
    }
}

EducateApp/ViewModels/Specialties/SortSpecialtyViewModel.cs
using EducateApp.Models.Enums;

namespace EducateApp.ViewModels.Specialties
{
    public class SortSpecialtyViewModel
    {
        public SpecialtySortState CodeSort { get; private set; }
        public SpecialtySortState NameSort { get; private set; }
        public SpecialtySortState FormOfStudySort { get; private set; }
        public SpecialtySortState Current { get; private set; }     // текущее значение сортировки

        public SortSpecialtyViewModel(SpecialtySortState sortOrder)
        {
            CodeSort = sortOrder == SpecialtySortState.CodeAsc ?
                SpecialtySortState.CodeDesc : SpecialtySortState.CodeAsc;

            NameSort = sortOrder == SpecialtySortState.NameAsc ?
                SpecialtySortState.NameDesc : SpecialtySortState.NameAsc;

            FormOfStudySort = sortOrder == SpecialtySortState.FormOfStudyAsc ?
                SpecialtySortState.FormOfStudyDesc : SpecialtySortState.FormOfStudyAsc;
            Current = sortOrder;
        }
    }
}

EducateApp/Controllers/SpecialtiesController.cs
using EducateApp.Models;
using EducateApp.Models.Data;
using EducateApp.Models.Enums;
using EducateApp.ViewModels.Specialties;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace EducateApp.Controllers
{
    [Authorize(Roles = "admin, registeredUser")]
    public class SpecialtiesController : Controller
    {
        private readonly ApplicationContext _context;
        private readonly UserManager<User> _userManager;

        public SpecialtiesController(ApplicationContext context, UserManager<User> user)
        {
            _context = context;
            _userManager = user;
        }

        // GET: Specialties
        public async Task<IActionResult> Index(string code, string name, short? formOfEdu,
            int page = 1,
            SpecialtySortState sortOrder = SpecialtySortState.CodeAsc)
        {
            IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            int pageSize = 10;

            //фильтрация
            IQueryable<Specialty> specialties = _context.Specialties
                .Include(s => s.FormOfStudy)                    // связываем специальности с формами обучения
                .Where(w => w.FormOfStudy.IdUser == user.Id);    // в формах обучения есть поле с внешним ключом пользователя

            if (!String.IsNullOrEmpty(code))
            {
                specialties = specialties.Where(p => p.Code.Contains(code));
            }
            if (!String.IsNullOrEmpty(name))
            {
                specialties = specialties.Where(p => p.Name.Contains(name));
            }
            if (formOfEdu != null && formOfEdu != 0)
            {
                specialties = specialties.Where(p => p.IdFormOfStudy == formOfEdu);
            }

            // сортировка
            switch (sortOrder)
            {
                case SpecialtySortState.CodeDesc:
                    specialties = specialties.OrderByDescending(s => s.Code);
                    break;
                case SpecialtySortState.NameAsc:
                    specialties = specialties.OrderBy(s => s.Name);
                    break;
                case SpecialtySortState.NameDesc:
                    specialties = specialties.OrderByDescending(s => s.Name);
                    break;
                case SpecialtySortState.FormOfStudyAsc:
                    specialties = specialties.OrderBy(s => s.FormOfStudy.FormOfEdu);
                    break;
                case SpecialtySortState.FormOfStudyDesc:
                    specialties = specialties.OrderByDescending(s => s.FormOfStudy.FormOfEdu);
                    break;
                default:
                    specialties = specialties.OrderBy(s => s.Code);
                    break;
            }

            // пагинация
            var count = await specialties.CountAsync();
            var items = await specialties.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();

            // формируем модель представления
            IndexSpecialtyViewModel viewModel = new()
            {
                PageViewModel = new(count, page, pageSize),
                SortSpecialtyViewModel = new(sortOrder),
                FilterSpecialtyViewModel = new(code, name, _context.FormsOfStudy.ToList(), formOfEdu),
                Specialties = items
            };
            return View(viewModel);
        }

        // GET: Specialties/Create
        public async Task<IActionResult> CreateAsync()
        {
            IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            // "выпадающий список"
            ViewData["IdFormOfStudy"] = new SelectList(_context.FormsOfStudy
                .Where(w => w.IdUser == user.Id), "Id", "FormOfEdu");
            return View();
        }

        // POST: Specialties/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateSpecialtyViewModel model)
        {
            IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            if (_context.Specialties
                .Where(f => f.FormOfStudy.IdUser == user.Id &&
                    f.Code == model.Code &&
                    f.Name == model.Name &&
                    f.IdFormOfStudy == model.IdFormOfStudy)
                .FirstOrDefault() != null)
            {
                ModelState.AddModelError("", "Введеная специальность уже существует");
            }

            if (ModelState.IsValid)
            {
                // если введены корректные данные,
                // то создается экземпляр класса модели Specialty, т.е. формируется запись в таблицу Specialties
                Specialty specialty = new()
                {
                    Code = model.Code,
                    Name = model.Name,

                    // с помощью свойства модели получим идентификатор выбранной формы обучения пользователем
                    IdFormOfStudy = model.IdFormOfStudy
                };

                _context.Add(specialty);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["IdFormOfStudy"] = new SelectList(
                _context.FormsOfStudy.Where(w => w.IdUser == user.Id),
                "Id", "FormOfEdu", model.IdFormOfStudy);
            return View(model);
        }

        // GET: Specialties/Edit/5
        public async Task<IActionResult> Edit(short? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var specialty = await _context.Specialties.FindAsync(id);
            if (specialty == null)
            {
                return NotFound();
            }
            EditSpecialtyViewModel model = new()
            {
                Id = specialty.Id,
                Code = specialty.Code,
                Name = specialty.Name,
                IdFormOfStudy = specialty.IdFormOfStudy
            };

            IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            // в списке в качестве текущего элемента устанавливаем значение из базы данных,
            // указываем параметр specialty.IdFormOfStudy
            ViewData["IdFormOfStudy"] = new SelectList(
                _context.FormsOfStudy.Where(w => w.IdUser == user.Id),
                "Id", "FormOfEdu", specialty.IdFormOfStudy);
            return View(model);
        }

        // POST: Specialties/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(short id, EditSpecialtyViewModel model)
        {
            Specialty specialty = await _context.Specialties.FindAsync(id);

            if (id != specialty.Id)
            {
                return NotFound();
            }

            IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            if (_context.Specialties
                .Where(f => f.FormOfStudy.IdUser == user.Id &&
                    f.Code == model.Code &&
                    f.Name == model.Name &&
                    f.IdFormOfStudy == model.IdFormOfStudy)
                .FirstOrDefault() != null)
            {
                ModelState.AddModelError("", "Введеная специальность уже существует");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    specialty.Code = model.Code;
                    specialty.Name = model.Name;
                    specialty.IdFormOfStudy = model.IdFormOfStudy;
                    _context.Update(specialty);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SpecialtyExists(specialty.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["IdFormOfStudy"] = new SelectList(
                _context.FormsOfStudy.Where(w => w.IdUser == user.Id),
                "Id", "FormOfEdu", specialty.IdFormOfStudy);
            return View(model);
        }

        // GET: Specialties/Delete/5
        public async Task<IActionResult> Delete(short? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var specialty = await _context.Specialties
                .Include(s => s.FormOfStudy)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (specialty == null)
            {
                return NotFound();
            }

            return View(specialty);
        }

        // POST: Specialties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(short id)
        {
            var specialty = await _context.Specialties.FindAsync(id);
            _context.Specialties.Remove(specialty);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Specialties/Details/5
        public async Task<IActionResult> Details(short? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var specialty = await _context.Specialties
                .Include(s => s.FormOfStudy)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (specialty == null)
            {
                return NotFound();
            }

EducateApp/Views/Specialties/Create.cshtml
@model EducateApp.ViewModels.Specialties.CreateSpecialtyViewModel
@{
    ViewData["Title"] = "Создание - Специальности";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item"><a asp-controller="Specialties" asp-action="Index">Специальности</a></li>
        <li class="breadcrumb-item active">Создание</li>
    </ol>
</nav>

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Добавление специальности
</h3>
<hr />

<div class="row">
    <div class="col-md-5">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdFormOfStudy" class="control-label"></label>
                <select asp-for="IdFormOfStudy" class="form-control" asp-items="ViewBag.IdFormOfStudy"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EducateApp/Views/Specialties/Delete.cshtml
@model EducateApp.Models.Data.Specialty
@{
    ViewData["Title"] = "Удаление - Специальности";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item"><a asp-controller="Specialties" asp-action="Index">Специальности</a></li>
        <li class="breadcrumb-item active">Удаление</li>
    </ol>
</nav>

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Удаление специальности
</h3>

<div>
    <h4>
        Вы уверены, что желаете удалить запись?<br />
        Все связанные данные будут удалены!
    </h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.FormOfStudy)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.FormOfStudy.FormOfEdu)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" />
    </form>
</div>

EducateApp/Views/Specialties/Details.cshtml
@model EducateApp.Models.Data.Specialty

@{
    ViewData["Title"] = "Специальности";
}

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Просмотр специальности
</h3>

<div>
    <dl class="row">
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.FormOfStudy)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.FormOfStudy.FormOfEdu)
        </dd>
    </dl>
</div>

EducateApp/Views/Specialties/Edit.cshtml
@model EducateApp.ViewModels.Specialties.EditSpecialtyViewModel
@{
    ViewData["Title"] = "Изменение - Специальности";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item"><a asp-controller="Specialties" asp-action="Index">Специальности</a></li>
        <li class="breadcrumb-item active">Изменение</li>
    </ol>
</nav>

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Изменение специальности
</h3>
<hr />

<div class="row">
    <div class="col-md-5">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdFormOfStudy" class="control-label"></label>
                <select asp-for="IdFormOfStudy" class="form-control" asp-items="ViewBag.IdFormOfStudy"></select>
                <span asp-validation-for="IdFormOfStudy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EducateApp/Views/Specialties/Index.cshtml
@model EducateApp.ViewModels.Specialties.IndexSpecialtyViewModel

@{
    ViewData["Title"] = "Специальности";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item active">Специальности</li>
    </ol>
</nav>
<h2>Специальности</h2>

<div class="d-flex justify-content-between">
    <div class="p-2">
        <ul class="nav">
            <li>
                <a class="btn text-dark" asp-action="Create">
                    <i class="far fa-plus-square"></i>  Добавить специальность
                </a>
            </li>
        </ul>
    </div>
    <div class="p-2">
        <form class="form-inline" asp-action="Index" method="get">
            <div class="form-actions no-color">
                <p>
                    <input type="text" name="code" placeholder="Индекс" value="@Model.FilterSpecialtyViewModel.SelectedCode" class="form-control" />
                    <input type="text" name="name" placeholder="Специальность" value="@Model.FilterSpecialtyViewModel.SelectedName" class="form-control" />

                    <select name="formOfEdu" asp-items="Model.FilterSpecialtyViewModel.FormOfStudies" class="form-control"></select>

                    <input type="submit" value="Поиск" class="btn btn-outline-success" /> |
                    <a class="=btn text-dark" asp-action="Index"><i class="fas fa-eraser"></i></a>
                </p>
            </div>
        </form>
    </div>
</div>

<div class="table-responsive">
    <table class="table table-bordered text-nowrap table-sm">
        <thead class="thead-light">
            <tr>
                <th>
                    <a asp-action="Index"
                       asp-route-sortOrder="@(Model.SortSpecialtyViewModel.CodeSort)"
                       asp-route-code="@(Model.FilterSpecialtyViewModel.SelectedCode)"
                       asp-route-name="@(Model.FilterSpecialtyViewModel.SelectedName)"
                       asp-route-formOfEdu="@(Model.FilterSpecialtyViewModel.FormOfEdu)">Индекс</a>
                </th>
                <th>
                    <a asp-action="Index"
                       asp-route-sortOrder="@(Model.SortSpecialtyViewModel.NameSort)"
                       asp-route-code="@(Model.FilterSpecialtyViewModel.SelectedCode)"
                       asp-route-name="@(Model.FilterSpecialtyViewModel.SelectedName)"
                       asp-route-formOfEdu="@(Model.FilterSpecialtyViewModel.FormOfEdu)">Специальность</a>
                </th>
                <th>
                    <a asp-action="Index"
                       asp-route-sortOrder="@(Model.SortSpecialtyViewModel.FormOfStudySort)"
                       asp-route-code="@(Model.FilterSpecialtyViewModel.SelectedCode)"
                       asp-route-name="@(Model.FilterSpecialtyViewModel.SelectedName)"
                       asp-route-formOfEdu="@(Model.FilterSpecialtyViewModel.FormOfEdu)">Форма обучения</a>
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Specialties)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Code)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FormOfStudy.FormOfEdu)
                    </td>
                    <td>
                        <a class="btn text-dark" asp-action="Details" asp-route-id="@item.Id" title="Посмотреть подробнее">
                            <i class="far fa-eye"></i>
                        </a> |
                        <a class="btn text-dark" asp-action="Edit" asp-route-id="@item.Id" title="Редактировать">
                            <i class="fas fa-pencil-alt"></i>
                        </a> |
                        <a class="btn text-dark" asp-action="Delete" asp-route-id="@item.Id" title="Удалить">
                            <i class="far fa-minus-square"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<nav>
    <ul class="pagination justify-content-center">
        @if (Model.PageViewModel.HasPreviousPage || Model.PageViewModel.HasNextPage)
        {
            @if (Model.PageViewModel.HasPreviousPage)
            {
                <li class="page-item">
                    <a class="page-link" asp-action="Index" title="Назад"
                       asp-route-page="@(Model.PageViewModel.PageNumber - 1)"
                       asp-route-sortOrder="@(Model.SortSpecialtyViewModel.Current)"
                       asp-route-code="@(Model.FilterSpecialtyViewModel.SelectedCode)"
                       asp-route-name="@(Model.FilterSpecialtyViewModel.SelectedName)"
                       asp-route-formOfEdu="@(Model.FilterSpecialtyViewModel.FormOfEdu)">
                        <i class="fas fa-chevron-left"></i>
                    </a>
                </li>
            }
            else
            {
                <li class="page-item disabled">
                    <a class="page-link" href="#">
                        <i class="fas fa-chevron-left"></i>
                    </a>
                </li>
            }
            @if (Model.PageViewModel.HasNextPage)
            {
                <li class="page-item">
                    <a class="page-link" asp-action="Index" title="Вперед"
                       asp-route-page="@(Model.PageViewModel.PageNumber + 1)"
                       asp-route-sortOrder="@(Model.SortSpecialtyViewModel.Current)"
                       asp-route-code="@(Model.FilterSpecialtyViewModel.SelectedCode)"
                       asp-route-name="@(Model.FilterSpecialtyViewModel.SelectedName)"
                       asp-route-formOfEdu="@(Model.FilterSpecialtyViewModel.FormOfEdu)">
                        <i class="fas fa-chevron-right"></i>
                    </a>
                </li>
            }
            else
            {
                <li class="page-item disabled">
                    <a class="page-link" href="#">
                        <i class="fas fa-chevron-right"></i>
                    </a>
                </li>
            }
        }
    </ul>
</nav>