EducateApp/Models/Data/Discipline.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EducateApp.Models.Data
{
    public class Discipline
    {
        // Key - поле первичный ключ
        // DatabaseGenerated(DatabaseGeneratedOption.Identity) - поле автоинкреметное
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Display(Name = "ИД")]
        public short Id { get; set; }

        [Required(ErrorMessage = "Введите индекс профессионального модуля")]
        [Display(Name = "Индекс профессионального модуля")]
        public string IndexProfModule { get; set; }

        [Required(ErrorMessage = "Введите название профессионального модуля")]
        [Display(Name = "Профессиональный модуль")]
        public string ProfModule { get; set; }

        [Required(ErrorMessage = "Введите индекс")]
        [Display(Name = "Индекс")]
        public string Index { get; set; }

        [Required(ErrorMessage = "Введите название")]
        [Display(Name = "Название")]
        public string Name { get; set; }

        //[Required(ErrorMessage = "Введите краткое название")]
        [Display(Name = "Краткое название")]
        public string ShortName { get; set; }

        [Required]
        public string IdUser { get; set; }

        // Навигационные свойства
        // свойство нужно для более правильного отображения данных в представлениях
        [ForeignKey("IdUser")]
        public User User { get; set; }
    }
}

EducateApp/ViewModels/Disciplines/CreateDisciplineViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace EducateApp.ViewModels.Disciplines
{
    public class CreateDisciplineViewModel
    {
        [Required(ErrorMessage = "Введите индекс профессионального модуля")]
        [Display(Name = "Индекс профессионального модуля")]
        public string IndexProfModule { get; set; }

        [Required(ErrorMessage = "Введите название профессионального модуля")]
        [Display(Name = "Название профессионального модуля")]
        public string ProfModule { get; set; }

        [Display(Name = "Индекс")]
        public string Index { get; set; }

        [Display(Name = "Название")]
        public string Name { get; set; }

        [Display(Name = "Краткое название")]
        public string ShortName { get; set; }
    }
}

EducateApp/ViewModels/Disciplines/EditDisciplineViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace EducateApp.ViewModels.Disciplines
{
    public class EditDisciplineViewModel
    {
        public short Id { get; set; }

        [Display(Name = "Индекс профессионального модуля")]
        public string IndexProfModule { get; set; }

        [Display(Name = "Название профессионального модуль")]
        public string ProfModule { get; set; }

        [Required(ErrorMessage = "Введите индекс")]
        [Display(Name = "Индекс")]
        public string Index { get; set; }

        [Required(ErrorMessage = "Введите название")]
        [Display(Name = "Название")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Введите краткое название")]
        [Display(Name = "Краткое название")]
        public string ShortName { get; set; }

        public string IdUser { get; set; }
    }
}

EducateApp/ViewModels/Disciplines/FilterDisciplineViewModel.cs
namespace EducateApp.ViewModels.Disciplines
{
    public class FilterDisciplineViewModel
    {
        public string SelectedIndexProfModule { get; private set; }
        public string SelectedProfModule { get; private set; }
        public string SelectedIndex { get; private set; }
        public string SelectedName { get; private set; }
        public string SelectedShortName { get; private set; }

        public FilterDisciplineViewModel(string indexProfModule, string profModule, string index, string name, string shortName)
        {
            SelectedIndexProfModule = indexProfModule;
            SelectedProfModule = profModule;
            SelectedIndex = index;
            SelectedName = name;
            SelectedShortName = shortName;
        }
    }
}

EducateApp/ViewModels/Disciplines/IndexDisciplineViewModel.cs
using EducateApp.Models.Data;
using System.Collections.Generic;

namespace EducateApp.ViewModels.Disciplines
{
    public class IndexDisciplineViewModel
    {
        public IEnumerable<Discipline> Disciplines { get; set; }
        public PageViewModel PageViewModel { get; set; }
        public FilterDisciplineViewModel FilterDisciplineViewModel { get; set; }
        public SortDisciplineViewModel SortDisciplineViewModel { get; set; }
    }
}

EducateApp/ViewModels/Disciplines/SortDisciplineViewModel.cs
using EducateApp.Models.Enums;

namespace EducateApp.ViewModels.Disciplines
{
    public class SortDisciplineViewModel
    {
        public DisciplineSortState IndexProfModuleSort { get; private set; }
        public DisciplineSortState ProfModuleSort { get; private set; }
        public DisciplineSortState IndexSort { get; private set; }
        public DisciplineSortState NameSort { get; private set; }
        public DisciplineSortState ShortNameSort { get; private set; }
        public DisciplineSortState Current { get; private set; }

        public SortDisciplineViewModel(DisciplineSortState sortOrder)
        {
            IndexProfModuleSort = sortOrder == DisciplineSortState.IndexProfModuleAsc ?
                DisciplineSortState.IndexProfModuleDesc : DisciplineSortState.IndexProfModuleAsc;

            ProfModuleSort = sortOrder == DisciplineSortState.ProfModuleAsc ?
                DisciplineSortState.ProfModuleDesc : DisciplineSortState.ProfModuleAsc;

            IndexSort = sortOrder == DisciplineSortState.IndexAsc ?
                DisciplineSortState.IndexDesc : DisciplineSortState.IndexAsc;

            NameSort = sortOrder == DisciplineSortState.NameAsc ?
                DisciplineSortState.NameDesc : DisciplineSortState.NameAsc;

            ShortNameSort = sortOrder == DisciplineSortState.ShortNameAsc ?
                DisciplineSortState.ShortNameDesc : DisciplineSortState.ShortNameAsc;

            Current = sortOrder;
        }
    }
}

EducateApp/Controllers/DisciplinesController.cs
using ClosedXML.Excel;
using EducateApp.Models;
using EducateApp.Models.Data;
using EducateApp.Models.Enums;
using EducateApp.ViewModels.Disciplines;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace EducateApp.Controllers
{
    [Authorize(Roles = "admin, registeredUser")]
    public class DisciplinesController : Controller
    {
        private readonly ApplicationContext _context;
        private readonly UserManager<User> _userManager;

        public DisciplinesController(ApplicationContext context, UserManager<User> user)
        {
            _context = context;
            _userManager = user;
        }

        // GET: Disciplines
        public async Task<IActionResult> Index(string indexProfModule, string profModule, string index, 
            string name, string shortName, int page = 1,
            DisciplineSortState sortOrder = DisciplineSortState.IndexProfModuleAsc)
        {
            // находим информацию о пользователе, который вошел в систему по его имени
            IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            int pageSize = 10;

            //фильтрация
            IQueryable<Discipline> disciplines = _context.Disciplines
                .Include(d => d.User)
                .Where(w => w.IdUser == user.Id);

            if (!String.IsNullOrEmpty(indexProfModule))
            {
                disciplines = disciplines.Where(p => p.IndexProfModule.Contains(indexProfModule));
            }
            if (!String.IsNullOrEmpty(profModule))
            {
                disciplines = disciplines.Where(p => p.ProfModule.Contains(profModule));
            }
            if (!String.IsNullOrEmpty(index))
            {
                disciplines = disciplines.Where(p => p.Index.Contains(index));
            }
            if (!String.IsNullOrEmpty(name))
            {
                disciplines = disciplines.Where(p => p.Name.Contains(name));
            }
            if (!String.IsNullOrEmpty(shortName))
            {
                disciplines = disciplines.Where(p => p.ShortName.Contains(shortName));
            }

            // сортировка
            switch (sortOrder)
            {
                case DisciplineSortState.IndexProfModuleDesc:
                    disciplines = disciplines.OrderByDescending(s => s.IndexProfModule);
                    break;
                case DisciplineSortState.ProfModuleAsc:
                    disciplines = disciplines.OrderBy(s => s.ProfModule);
                    break;
                case DisciplineSortState.ProfModuleDesc:
                    disciplines = disciplines.OrderByDescending(s => s.ProfModule);
                    break;
                case DisciplineSortState.IndexAsc:
                    disciplines = disciplines.OrderBy(s => s.Index);
                    break;
                case DisciplineSortState.IndexDesc:
                    disciplines = disciplines.OrderByDescending(s => s.Index);
                    break;
                case DisciplineSortState.NameAsc:
                    disciplines = disciplines.OrderBy(s => s.Name);
                    break;
                case DisciplineSortState.NameDesc:
                    disciplines = disciplines.OrderByDescending(s => s.Name);
                    break;
                case DisciplineSortState.ShortNameAsc:
                    disciplines = disciplines.OrderBy(s => s.ShortName);
                    break;
                case DisciplineSortState.ShortNameDesc:
                    disciplines = disciplines.OrderByDescending(s => s.ShortName);
                    break;
                default:
                    disciplines = disciplines.OrderBy(s => s.IndexProfModule);
                    break;
            }

            // пагинация
            var count = await disciplines.CountAsync();
            var items = await disciplines.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();

            // формируем модель представления
            IndexDisciplineViewModel viewModel = new()
            {
                PageViewModel = new(count, page, pageSize),
                SortDisciplineViewModel = new(sortOrder),
                FilterDisciplineViewModel = new(indexProfModule, profModule, index, name, shortName),
                Disciplines = items
            };
            return View(viewModel);
        }

        // GET: Disciplines/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Disciplines/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateDisciplineViewModel model)
        {
            IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            if (_context.Disciplines
                .Where(f => f.IdUser == user.Id &&
                 f.IndexProfModule == model.IndexProfModule &&
                 f.ProfModule == model.ProfModule &&
                 f.Index == model.Index && f.Name == model.Name &&
                 f.ShortName == model.ShortName).FirstOrDefault() != null)
            {
                ModelState.AddModelError("", "Введенный вид дисциплины уже существует");
            }

            if (ModelState.IsValid)
            {
                Discipline discipline = new()
                {
                    IndexProfModule = model.IndexProfModule,
                    ProfModule = model.ProfModule,
                    Index = model.Index,
                    Name = model.Name,
                    ShortName = model.ShortName,
                    IdUser = user.Id
                };

                _context.Add(discipline);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: Disciplines/Edit/5
        public async Task<IActionResult> Edit(short? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var disciplines = await _context.Disciplines.FindAsync(id);
            if (disciplines == null)
            {
                return NotFound();
            }

            EditDisciplineViewModel model = new()
            {
                Id = disciplines.Id,
                IndexProfModule = disciplines.IndexProfModule,
                ProfModule = disciplines.ProfModule,
                Index = disciplines.Index,
                Name = disciplines.Name,
                ShortName = disciplines.ShortName,
                IdUser = disciplines.IdUser
            };

            return View(model);
        }

        // POST: Disciplines/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(short id, EditDisciplineViewModel model)
        {
            Discipline discipline = await _context.Disciplines.FindAsync(id);

            if (id != discipline.Id)
            {
                return NotFound();
            }

            IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            if (_context.Disciplines
                .Where(f => f.IdUser == user.Id &&
                 f.IndexProfModule == model.IndexProfModule &&
                 f.ProfModule == model.ProfModule &&
                 f.Index == model.Index && f.Name == model.Name &&
                 f.ShortName == model.ShortName).FirstOrDefault() != null)
            {
                ModelState.AddModelError("", "Введенный вид дисциплины уже существует");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    discipline.IndexProfModule = model.IndexProfModule;
                    discipline.ProfModule = model.ProfModule;
                    discipline.Index = model.Index;
                    discipline.Name = model.Name;
                    discipline.ShortName = model.ShortName;
                    _context.Update(discipline);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DisciplineExists(discipline.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: Disciplines/Delete/5
        public async Task<IActionResult> Delete(short? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var discipline = await _context.Disciplines
                .Include(d => d.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (discipline == null)
            {
                return NotFound();
            }

            return View(discipline);
        }

        // POST: Disciplines/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(short id)
        {
            var discipline = await _context.Disciplines.FindAsync(id);
            _context.Disciplines.Remove(discipline);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Disciplines/Details/5
        public async Task<IActionResult> Details(short? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var discipline = await _context.Disciplines
                .Include(d => d.User)

EducateApp/Views/Disciplines/Create.cshtml
@model EducateApp.ViewModels.Disciplines.CreateDisciplineViewModel

@{
    ViewData["Title"] = "Создание - Дисциплины";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item"><a asp-controller="Disciplines" asp-action="Index">Дисциплины</a></li>
        <li class="breadcrumb-item active">Создание</li>
    </ol>
</nav>

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Добавление дисциплины
</h3>
<hr />

<div class="row">
    <div class="col-md-5">
        <form method="post" asp-controller="Disciplines" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IndexProfModule" class="control-label"></label>
                <input asp-for="IndexProfModule" class="form-control" />
                <span asp-validation-for="IndexProfModule" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProfModule" class="control-label"></label>
                <input asp-for="ProfModule" class="form-control" />
                <span asp-validation-for="ProfModule" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Index" class="control-label"></label>
                <input asp-for="Index" class="form-control" />
                <span asp-validation-for="Index" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShortName" class="control-label"></label>
                <input asp-for="ShortName" class="form-control" />
                <span asp-validation-for="ShortName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EducateApp/Views/Disciplines/Delete.cshtml
@model EducateApp.Models.Data.Discipline

@{
    ViewData["Title"] = "Удаление - Дисциплины";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item"><a asp-controller="Disciplines" asp-action="Index">Дисциплины</a></li>
        <li class="breadcrumb-item active">Удаление</li>
    </ol>
</nav>

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Удаление дисциплины
</h3>

<div>
    <h4>
        Вы уверены, что желаете удалить запись?<br />
        Все связанные данные будут удалены!
    </h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.IndexProfModule)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.IndexProfModule)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.ProfModule)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.ProfModule)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Index)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.Index)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.ShortName)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.ShortName)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" />
    </form>
</div>

EducateApp/Views/Disciplines/Details.cshtml
@model EducateApp.Models.Data.Discipline

<div class="modal-content">
    <div class="modal-header">
        <h4 class="modal-title">Просмотр группы</h4>
        <button type="button" class="close" data-dismiss="modal">
            <i class="fas fa-times"></i>
        </button>
    </div>

    <div class="modal-body">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.IndexProfModule)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.IndexProfModule)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.ProfModule)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ProfModule)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Index)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Index)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.ShortName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ShortName)
            </dd>
        </dl>
    </div>
</div>

EducateApp/Views/Disciplines/Edit.cshtml
@model EducateApp.ViewModels.Disciplines.EditDisciplineViewModel

@{
    ViewData["Title"] = "Изменение - Дисциплины";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Главная</a></li>
        <li class="breadcrumb-item"><a asp-controller="Disciplines" asp-action="Index">Дисциплины</a></li>
        <li class="breadcrumb-item active">Изменение</li>
    </ol>
</nav>

<h3>
    <a class="btn text-dark" asp-action="Index" title="Вернуться к списку">
        <i class="fas fa-arrow-left"></i>
    </a>
    Изменение дисциплины
</h3>
<hr />

<div class="row">
    <div class="col-md-5">
        <form asp-controller="Disciplines" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="IndexProfModule" class="control-label"></label>
                <input asp-for="IndexProfModule" class="form-control" />
                <span asp-validation-for="IndexProfModule" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProfModule" class="control-label"></label>
                <input asp-for="ProfModule" class="form-control" />
                <span asp-validation-for="ProfModule" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Index" class="control-label"></label>
                <input asp-for="Index" class="form-control" />
                <span asp-validation-for="Index" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShortName" class="control-label"></label>
                <input asp-for="ShortName" class="form-control" />
                <span asp-validation-for="ShortName" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="IdUser" />
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}